development:
  adapter: mysql
  encoding: utf8
  database: patrono_development
  username: root
  password: riopro
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  database: patrono_test
  username: root
  password: riopro
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  database: patrono
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
